### ISSUE TITLE
Inconsistent syntax highlighting of optional chaining (?.) operator.

### ISSUE THREAD

**Issue by wcroteau** [ionztorm/ionztorm-theme#1]
The optional chaining (?.) operator doesn't appear to have correct syntax highlighting...

Here's what I see now:

![image](https://github.com/user-attachments/assets/1e19ba57-3ee4-404c-95f2-d4b72c9749b0)

Note the dim color.  This seems to be inconsistent with other operators which have a "salmon-ish" colour:

![image](https://github.com/user-attachments/assets/aceadc78-40ea-4412-a9de-7c9886149df6)

This is not a horrible problem in normal code views (just inconsistent) however when I diff my code, it blends completely into the background making it VERY difficult to see what's been changed.

See this diff where I've inserted a ? before the . in ``node.parent``:

![image](https://github.com/user-attachments/assets/e0c9bb6f-52f8-408c-91a5-5b05aea819ec)

This is causing me WAY too many braincells to pick out what has changed (and I have sooo few to spare) and is thus error prone I find.

Note: This is especially noticeable (or ironically NOT noticeable) when the line in question is the "current" change.

**Comment by leonlonsdale** [comment]
v 0.3.6 has just been pushed. Colour switched from grey to salmon for "punctuation.accessor.optional".

Let me know it this sorts it for you

**Comment by wcroteau** [comment]
Sweet!!  Waiting for it to be updated on the extension marketplace!

**Comment by leonlonsdale** [comment]
Should now be live 👍

**Comment by wcroteau** [comment]
Using v0.3.10 (latest I believe) and this issue has cropped back up, optional chaining operator is grey-ish instead of salmon again...

![image](https://github.com/user-attachments/assets/5bad38e2-2676-4d7e-9040-c2e248a98b50)
