### ISSUE TITLE
Poor contrast in diff'ed comments

### ISSUE THREAD

**Issue by wcroteau** [ionztorm/ionztorm-theme#2]
In the diff viewer if the change is a comment (most notably in commented out code) the contrast is so low that I can't see the comment.

This is important for me because I frequently need to be able to see/read the comments in diff viewer to decide if that block needs to be retained or not...

It would be good if those comments were legible.  Here's an example:

![image](https://github.com/user-attachments/assets/82ecad73-b82c-4803-a846-d5dfcfec5fe3)

By contract here's an example of the same line in my second-favourite theme:

![image](https://github.com/user-attachments/assets/c6f5b49e-adf2-4d35-a2de-36de6c6ffabd)

**Comment by leonlonsdale** [comment]
Just pushed an update, let me know if this fixes it. Looks ok my end but may need further tweaks as I also had to adjust the diff -green highlight shade. Update should be available in marketplace in approx 10 minutes.

**Comment by wcroteau** [comment]
Diff'd comments now are very legible thanks!

However as a result (maybe) of this change, there are other problems with comments.

Here's an example of a comment that has been "selected" (highlight with the mouse)

![image](https://github.com/user-attachments/assets/28af4131-0e8b-4bd6-8f28-e4125e8abfa6)

Still not really usable in that state - I still think that root of these issues is the base colour of comments...  They're generally hard to see in any state I find.  Like here:

![image](https://github.com/user-attachments/assets/2b1efb84-f57a-4247-b7b4-7a4e34bfa724)

**Comment by leonlonsdale** [comment]
Comments are now a deep shade of purple-pink. Looks clear at my end, let me know how it works for you.

**Comment by wcroteau** [comment]
Looks great, clear, easy to read - very comment-y!!

**Comment by leonlonsdale** [comment]
Awesome!
