### ISSUE TITLE
More contrast issues with tags in TSX 

### ISSUE THREAD

**Issue by wcroteau** [ionztorm/ionztorm-theme#3]
Poor contrast in TSX tags (maybe JSX too?)

An example in a regular code file (which isn't too bad):

![image](https://github.com/user-attachments/assets/5854d042-eb24-4c1c-a765-91ef4dcb582c)

You can see that the HTML <> tags are very faint although legible, again not too but and not my real complaint.

However, here's what the same code looks like when I diff the file:

![image](https://github.com/user-attachments/assets/3be27cb5-c97c-489d-afb0-feeeb8114939)

It's completely illegible and I spend way too much time trying to figure out where my tags are...

**Comment by leonlonsdale** [comment]
Published a fix. HTML tag open/close now uses the comment colour.
